export default [
  // Mythological
  'Zeus',
  'Hades',
  'Hercules',
  'Cerberus',
  'Bahamut',
  'A dragon',
  'A chimera',
  'A unicorn',
  'A centaur',
  'A basilisk',
  'A giant cyclops',
  // Cryptids
  'A chupacabra',
  'The Lock Ness Monster',
  'Big Foot',
  'A yeti',
  'Mothman',
  // Fantasy
  'A werewolf',
  'A vampire',
  'An elf',
  'An ogre',
  'A goblin',
  'A griffin',
  'A zombie',
  'A kraken',
  // Sci-fi
  'A ghost',
  'A demon',
  'An alien',
  'A shapeshifter',
  'A body-snatcher',
  'Cthulhu',
  // People
  'A pirate',
  'A ninja',
  'A samurai',
  'A knight',
  'A viking',
  'Sherlock Holmes',
  'Hercule Poirot',
  // Animals
  'A rabid squirrel',
  'A raccoon with a knife',
  'An angry mongoose',
  'A king cobra',
  'A komodo dragon',
  'A silverback gorilla',
  'A hippopotamus',
  'A lion, tiger, and bear',
];